### ISSUE TITLE
Temp Reading

### ISSUE THREAD

**Issue by drewharbin** [IndyJoeA/cbpi_iSpindel#1]
In CBP I have my temp units set to F but my ispindel is still pulling onto the dashboard in Celsius.  I see your screenshot is showing in Fahrenheit and looks to have an accurate temperature.  What am I doing wrong?  Also is there an example of a polynomial for the ispindel to show specific gravity everything I'm finding is degrees Plato. 

Thanks,
Drew

**Comment by IndyJoeA** [comment]
Check whether your iSpindel is converting the values from C to F.  The iSpindel has to also be set to send the value as F.  The plugin does not convert C readings to F, it just shows whatever temp units were selected and assumes the same unit was selected on the iSpindel.

**Comment by drewharbin** [comment]
Is this something I do in ispindel.cpp?  I've been looking for this for awhile and realize it isn't an issue with your plugin, but you are the first I've ran across with an ispindel converting and sending in F. could you send me a brief instruction drew@harbingerbeer.com

**Comment by IndyJoeA** [comment]
I'm not sure if the iSpindel is able to convert the values from C to F itself.  You would have to check out the latest release notes from that project to see if they have implemented that yet.  The screenshots I posted are just made with test data, as I do not have a real iSpindel to test with, so I use fake data.
