### ISSUE TITLE
Does not support ^ character

### ISSUE THREAD

**Issue by kjenset** [IndyJoeA/cbpi_iSpindel#2]
Hi

As I understand does not your plugin support ^ character in Polynomial? 
My Polynomial is like this: 0.003268271*tilt^2 + 0.224181018*tilt - 6.761043052

How can i fix this?

Regards
Kjenset

**Comment by IndyJoeA** [comment]
You will have to enter it like this: 0.003268271*tilt*tilt + 0.224181018*tilt - 6.761043052

**Comment by kjenset** [comment]
thanx for your help!
