### ISSUE TITLE
no values shown in CPB3.0

### ISSUE THREAD

**Issue by stefanK74** [IndyJoeA/cbpi_iSpindel#3]
I´m experiencing issues with the CBP3.0 plugin - no values are shown in the interface, although installing and configuring the plugin work fine, iSpindel is configured to connect to CPB. I am running the latest firmware on iSpindel.
iSpindel does work fine when connected to Ubidots.
When looking into the CPB logs-folder there is no sensor log-file created.
Any advice would be highly appreciated. Thanks!

**Comment by stefanK74** [comment]
Hope this helps:

     FW 5.8.5
2.2.1(cfd48f3)
Worker run!
Boot-Mode: 5
mounting FS... mounted!
reading config file
opened config file

parsed json
offsets not available
parsed config:
{"Name":"iSpindel000","Token":"BBFF-0EMbSc4PP36dOPPd1eaawjobQeFZKL","Sleep":5,"Server":"10.0.0.17","API":2,"Port":5000,"URL":"","DB":"ispindel","Job":"ispindel","Instance":"000","Vfact":191.8,"TS":0,"SSID":"Stefans iNet","PSK":"pass","POLY":"0.00438*(tilt)*(tilt)+0.13647","aX":0,"aY":0,"aZ":0}
                                                                                                 woken from deepsleep, normal mode
Spl 0: 65.15
Spl 1: 65.15
Spl 2: 65.18
Spl 3: 65.14
Spl 4: 65.15
Spl 5: 65.17
Spl 6: 65.16

a: -8812        12672   694     absTilt: 65.15  T: 31.67        V: 4.21 owT: 29.62      Gravity: 18.73
After waiting 1500ms, result 3
IP: 10.0.0.2

calling CraftbeerPi
{"name":"iSpindel000","ID":5173834,"token":"BBFF-0EMbSc4PP36dOPPd1eaawjobQeFZKL","angle":65.15455,"temperature":29.625,"battery":4.207508,"gravity":18.73007,"interval":5,"RSSI":-44}HTTPAPI: posting
code: 204

Final-sleep: 5s; RT:3348

**Comment by IndyJoeA** [comment]
Can you post screenshots of the CBPi config page for your iSpindel, as well as the config page from the iSpindel device?

**Comment by stefanK74** [comment]
Thanks for the hint to compare both pages! Obviously in CBPi config, iSpindel´s name needs to match with the name in the config of the iSpindel device. Values are displayed and it is working like a charm now!

**Comment by IndyJoeA** [comment]
Glad that helped!
